### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by amiltonwong** [elliottd/GroundedTranslation#18]
Hi, @elliottd 

I came across the following error when issuing training command:
Could you suggest me how to fix it?    THX~

======================================================

root@milton-OptiPlex-9010:/data/GroundedTranslation# THEANO_FLAGS=floatX=float32,device=gpu0 python train.py --dataset iaprtc12_eng --hidden_size=256 --fixed_seed --run_string=fixed_seed-eng256mlm
Using Theano backend.
Using gpu device 0: GeForce GTX TITAN (CNMeM is disabled, CuDNN 4007)
INFO:__main__:Run arguments:
INFO:__main__:clipnorm: -1
INFO:__main__:small_val: False
INFO:__main__:fixed_seed: True
INFO:__main__:dataset: iaprtc12_eng
INFO:__main__:generate_from_N_words: 0
INFO:__main__:patience: 10
INFO:__main__:enable_val_pplx: True
INFO:__main__:use_predicted_tokens: False
INFO:__main__:no_image: False
INFO:__main__:max_epochs: 50
INFO:__main__:predefined_epochs: False
INFO:__main__:gru: False
INFO:__main__:generation_timesteps: 30
INFO:__main__:source_vectors: None
INFO:__main__:debug: False
INFO:__main__:supertrain_datasets: None
INFO:__main__:run_string: fixed_seed-eng256mlm
INFO:__main__:optimiser: adam
INFO:__main__:lr: None
INFO:__main__:beta2: None
INFO:__main__:beta1: None
INFO:__main__:hidden_size: 256
INFO:__main__:source_enc: None
INFO:__main__:epsilon: None
INFO:__main__:batch_size: 100
INFO:__main__:source_type: None
INFO:__main__:stopping_loss: bleu
INFO:__main__:l2reg: 1e-08
INFO:__main__:dropin: 0.5
INFO:__main__:init_from_checkpoint: None
INFO:__main__:big_batch_size: 10000
INFO:__main__:h5_writeable: False
INFO:__main__:small: False
INFO:__main__:unk: 3
INFO:__main__:num_sents: 5
INFO:__main__:existing_vocab: 
INFO:data_generator:Initialising data generator
INFO:data_generator:Train/val dataset: iaprtc12_eng
INFO:data_generator:Input gold descriptions
INFO:data_generator:Extracting vocabulary
INFO:data_generator:Pickling dictionary to checkpoint/fixed_seed-eng256mlm/vocabulary.pk
INFO:data_generator:Max seq length 63, setting max_seq_len to 65
INFO:data_generator:Split sizes {'test': 1962, 'train': 15897, 'val': 1766}
INFO:data_generator:Number of words 3953 -> 1764
INFO:data_generator:Retained / Original Tokens: 272175 / 275467 (98.80 pc)
INFO:data_generator:Average train sentence length: 17.33 tokens
INFO:data_generator:Making data for val
INFO:models:Building Keras model...
INFO:models:Using image features: True
INFO:models:Using source language features: False
INFO:models:... visual: adding image features as input features
Traceback (most recent call last):
  File "train.py", line 282, in <module>
    model.train_model()
  File "train.py", line 85, in train_model
    use_image=self.use_image)
  File "/data/GroundedTranslation/models.py", line 98, in buildKerasModel
    model.add(Activation('time_distributed_softmax'))
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 734, in __init__
    self.activation = activations.get(activation)
  File "/usr/local/lib/python2.7/dist-packages/keras/activations.py", line 47, in get
    return get_from_module(identifier, globals(), 'activation function')
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/generic_utils.py", line 14, in get_from_module
    str(identifier))
Exception: Invalid activation function: time_distributed_softmax

======================================================

**Comment by elliottd** [comment]
You are using a version of Keras > 0.1.3.

`time_distributed_softmax` was already in deprecation mode back then, and the recommended activation function was just `softmax`.

Pull the code again and it should work with a newer version of Keras.

**Comment by amiltonwong** [comment]
Hi, @elliottd ,

Thanks for your quick reply. After I modify the "models.py" as https://github.com/elliottd/GroundedTranslation/commit/fc108773cd6e9467a19c0b75436a09a3692f00e1
, it passes that issue. However, a new error comes out: 
>> OSError: [Errno 12] Cannot allocate memory

The detailed log is here:
https://gist.github.com/amiltonwong/6ea97505483852e1ed956b4cf92d5445

What's the minimum ram memory required? My machine has only 8GB ram memory.

THX~

**Comment by elliottd** [comment]
@amiltonwong the current code needs a lot more memory than that because we process all the validation data in a single batch. This was never a big problem for us on the IAPR-TC12 dataset but we're running into some memory-management issues with the new multilingual Flickr30K datasets.

We are working on reducing the memory footprint in the `experimental_datagen` branch but I don't think we can easily get it down to < 8GB. It might be possible with small minibatches. I'll ping you when the new code has been merged into the main code.
